#!/usr/bin/env python3
"""
PowerShell Formatter
"""

class PS1Formatter:
    def format(self, payload):
        """Format as PowerShell script"""
        return f"""
# PowerShell Payload - Generated by PySploit
{payload}
"""